#!/bin/bash
# This script will download the base system for you.
source /lib/archosu-main


introduction() {
	dialog --backtitle "$tit" --title "Archosu! installation" --msgbox "This part of the installation will install the base system to your disk." 6 70
}

download() {
	sudo pacstrap /mnt "$@"
	echo -e "\\n$enter"
}

chrootfiles() {
	cp -r /lib/archosu-chroot/lib/* /mnt/
	arch-chroot /mnt /bin/bash /lib/archosu-utils-chroot
}

introduction
download base base-devel networkmanager dialog 2>&1 | dialog --title "Installing all the needed packages for the OS." --backtitle "$tit" --programbox 25 90
chrootfiles

# Reboot prompt
dialog --ok-label "Reboot now" --nocancel --pause "Rebooting in 10 seconds...\\nBe sure, that your computer will boot from your drive you have installed.\\n\\nDO NOT UNPLUG YOUR BOOT DRIVE, OTHERWISE THE RESTARTING PROCESS WILL FREEZE (you can unplug the boot drive once you've exited from this boot session)." 15 71 10
