#!/bin/bash
# This script will execute all archosu-* scripts in right order.
source /lib/archosu-main

checkversion() {
	case "$uptodate" in
		yes) ;;
		*) echo "Your version of archosu-architect isn't up-to-date." && sleep 2 ;;
	esac
}

introduction() {
	dialog --backtitle "$tit" --title "Archosu! installation" --msgbox "Welcome to Archosu! \\nThis script will do all the installation for you, but you'll still have to do some things (like preparing drives for installation), but the script has all the scripts prepared." 8 80
}

checkversion
exec /lib/archosu-utils-disk
